### ISSUE TITLE
Does not generate folder for configuration file

### ISSUE THREAD

**Issue by dysfwombat** [carcarjg/Tortoise911#2]
folder c:\nyxtel\ does not get generated and file config.nxt has to be placed manually in c:\nyxtel\

**Comment by nyxymuffin** [comment]
Internal note: User is an idiot

oh wait these are public :3 


TODO: Move c:\nyxtel\ config DIR to %appdata% or somewhere else that doesnt require UAC auth

**Comment by nyxymuffin** [comment]
Fixed with Commit 0ca9e12f40edf7c536c446d70b3c283a9955c78e
